[build]
  command = "echo 'No build needed for static site'"
  publish = "./"

[redirects]
  / = /Block.html
  /blog/* = /Block.html
  /glosario/* = /Block.html
  /contacto/* = /Block.html
  /acerca-de/* = /Block.html
